{
 "title": "Near Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Peer Details",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "near_peer_connections_total{app=\"near\"}",
     "legendFormat": "{{name}} Peer Connections"
    },
    {
     "expr": "peer_block_received_total{job=\"staging-testnet\"}",
     "legendFormat": "{{name}} Peer Blocks Received"
    },
    {
     "expr": "peer_transaction_received_total{job=\"staging-testnet\"}",
     "legendFormat": "{{name}} Peer Transaction Received"
    },
    {
     "expr": "peer_message_received_total{job=\"staging-testnet\"}",
     "legendFormat": "{{name}} Peer Messages Received"
    },
    {
     "expr": "peer_data_received_bytes{job=\"staging-testnet\"}",
     "legendFormat": "{{name}} Peer Bytes Received"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(near_block_height_head{app=\"near\"})"
    }
   ]
  },
  {
   "title": "Header Head Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(near_header_head_height{app=\"near\"})"
    }
   ]
  },
  {
   "title": "HTTP Status Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(near_http_status_requests_total{app=\"near\"})"
    }
   ]
  },
  {
   "title": "HTTP Prometheus Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(near_http_prometheus_requests_total{app=\"near\"})"
    }
   ]
  }
 ]
}